# Puerta MongoDB Load Balancer Configuration
# Testing against local MongoDB cluster: localhost:27020,27021,27022

[server]
listen_addr = "0.0.0.0:27018"
max_connections = 1000
connection_timeout_sec = 30
worker_threads = 4

[proxy]
mode = "mongodb"
mongos_endpoints = [
    "127.0.0.1:27020",
    "127.0.0.1:27021", 
    "127.0.0.1:27022"
]
session_affinity = true
session_timeout_sec = 1800

[health]
interval_sec = 10
timeout_sec = 5
failure_threshold = 3
success_threshold = 2

[logging]
level = "debug"
format = "text"
stdout = true