[server]
listen_addr = "127.0.0.1:27018"
max_connections = 1000
connection_timeout_sec = 60

[proxy]
mode = "mongodb"
mongos_endpoints = [
    "127.0.0.1:27017",
]
session_affinity = true
session_timeout_sec = 3600

[health]
interval_sec = 10
timeout_sec = 5
failure_threshold = 3
success_threshold = 2

[logging]
level = "info"
format = "text"
stdout = true
