# Puerta configuration for MongoDB Sharded Cluster load balancing
# This configuration enables session-aware load balancing across multiple mongos instances

[server]
listen_addr = "0.0.0.0:27016"
max_connections = 10000
connection_timeout_sec = 30
worker_threads = 4  # Optional: defaults to number of CPU cores

# Optional daemon mode configuration
# [server.daemon]
# enabled = true                           # Set to true to run as daemon
# pid_file = "/var/run/puerta.pid"         # PID file path
# error_log = "/var/log/puerta/error.log"  # Error log file
# upgrade_sock = "/var/run/puerta_upgrade.sock"  # Upgrade socket path
# user = "puerta"                          # User to run as (optional)
# group = "puerta"                         # Group to run as (optional)

[proxy]
mode = "mongodb"
# List of mongos instances to load balance across
mongos_endpoints = [
    "127.0.0.1:27017",
    "127.0.0.1:27018", 
    "127.0.0.1:27019"
]
# Enable session affinity - CRITICAL for MongoDB cursor consistency
session_affinity = true
# Session timeout in seconds
session_timeout_sec = 1800

[health]
# Health check interval in seconds
interval_sec = 10
# Health check timeout in seconds
timeout_sec = 5
# Number of consecutive failures before marking unhealthy
failure_threshold = 3
# Number of consecutive successes before marking healthy  
success_threshold = 2

[logging]
level = "debug"
format = "text"
stdout = true
# Optional: log to file
# file = "/var/log/puerta/puerta.log"